### ISSUE TITLE
Digest doesn't run

### ISSUE THREAD

**Issue by Radu-Raicea** [zlwaterfield/radar#9]
The digest doesn't run automatically on a daily basis. It only works when I click test.

@zlwaterfield

**Comment by zlwaterfield** [comment]
Hey @Radu-Raicea - i'll take a look at this tonight!

**Comment by zlwaterfield** [comment]
@Radu-Raicea I pushed some changes and looks to be working now, can you give it a try?

**Comment by zlwaterfield** [comment]
Closing because this should be resolved.

**Comment by Radu-Raicea** [comment]
It's still not working, we're not getting the daily digest, and the test button doesn't send the notification anymore.
